# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Compilation actions to run on pull requests

name: Compile

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  standalone_kernel:
    name: kernel
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [RISCV64]
        compiler: [gcc]
    steps:
    - uses: actions/checkout@v2
    - uses: hensoldt-cyber/ci-actions/standalone-kernel@patch-axel-6a
      with:
        ARCH: ${{ matrix.arch }}
        COMPILER: ${{ matrix.compiler }}
